[buildPlans.ZhiMaMono]
family = 'ZhiMa Mono'
spacing = 'fixed'
serifs = 'sans'
noCvSs = true
exportGlyphNames = false

[buildPlans.ZhiMaMono.variants.design]
# cv01 = 1
one = 'no-base'
# cv02 = 1
two = 'straight-neck-serifless'
# cv03 = 3
three = 'two-arcs'
# cv04 = 1
four = 'closed-serifless'
# cv05 = 1
five = 'upright-arched-serifless'
# cv06 = 3
six = 'straight-bar'
# cv07 = 1
seven = 'straight-serifless'
# cv08 = 2
eight = 'two-circles'
# cv09 = 3
nine = 'straight-bar'
# cv10 = 22
zero = 'oval-tall-slashed'
# cv11 = 1
capital-a = 'straight-serifless'
# cv12 = 1
capital-b = 'standard-serifless'
# cv13 = 1
capital-c = 'serifless'
# cv14 = 1
capital-d = 'standard-serifless'
# cv15 = 1
capital-e = 'serifless'
# cv16 = 1
capital-f = 'serifless'
# cv17 = 20
capital-g = 'toothless-rounded-serifless-hooked'
# cv18 = 1
capital-h = 'serifless'
# cv19 = 2
capital-i = 'serifed'
# cv20 = 2
capital-j = 'serifed'
# cv21 = 1
capital-k = 'straight-serifless'
# cv22 = 1
capital-l = 'serifless'
# cv23 = 4
capital-m = 'flat-bottom-serifless'
# cv24 = 1
capital-n = 'standard-serifless'
# cv25 = 1
capital-p = 'closed-serifless'
# cv26 = 5
capital-q = 'crossing'
# cv27 = 1
capital-r = 'straight-serifless'
# cv28 = 1
capital-s = 'serifless'
# cv29 = 1
capital-t = 'serifless'
# cv30 = 12
capital-u = 'toothless-rounded-serifless'
# cv31 = 1
capital-v = 'straight-serifless'
# cv32 = 7
capital-w = 'straight-flat-top-serifless'
# cv33 = 1
capital-x = 'straight-serifless'
# cv34 = 1
capital-y = 'straight-serifless'
# cv35 = 1
capital-z = 'straight-serifless'
# cv36 = 1
a = 'double-storey-serifless'
# cv37 = 1
b = 'toothed-serifless'
# cv38 = 1
c = 'serifless'
# cv39 = 1
d = 'toothed-serifless'
# cv40 = 1
e = 'flat-crossbar'
# cv41 = 12
f = 'flat-hook-serifless-crossbar-at-x-height'
# cv42 = 3
g = 'single-storey-serifless'
# cv43 = 1
h = 'straight-serifless'
# cv44 = 5
i = 'serifed'
# cv45 = 6
j = 'flat-hook-serifed'
# cv46 = 1
k = 'straight-serifless'
# cv47 = 5
l = 'serifed'
# cv48 = 1
m = 'serifless'
# cv49 = 1
n = 'straight-serifless'
# cv50 = 1
p = 'eared-serifless'
# cv51 = 1
q = 'straight-serifless'
# cv52 = 9
r = 'hookless-serifless'
# cv53 = 1
s = 'serifless'
# cv54 = 8
t = 'flat-hook-short-neck'
# cv55 = 1
u = 'toothed-serifless'
# cv56 = 1
v = 'straight-serifless'
# cv57 = 7
w = 'straight-flat-top-serifless'
# cv58 = 1
x = 'straight-serifless'
# cv59 = 4
y = 'straight-turn-serifless'
# cv60 = 1
z = 'straight-serifless'
# VDAC = 1 . , : ;
punctuation-dot = 'round'
# VSAA = 2 ~
tilde = 'low'
# VSAB = 3 *
asterisk = 'penta-low'
# VSAC = 2 _
underscore = 'high'
# VSAD = 1 ^
caret = 'high'
# VSAE = 1 `
ascii-grave = 'straight'
# VSAF = 1 '
ascii-single-quote = 'straight'
# VSAG = 1 ()
paren = 'normal'
# VSAH = 1 {}
brace = 'straight'
# VSAJ = 1 #
number-sign = 'upright'
# VSAK = 1 &
ampersand = 'closed'
# VSAL = 5 @
at = 'fourfold'
# VSAM = 3 $
dollar = 'through'
# VSAO = 3 %
percent = 'rings-continuous-slash'
# VSAP = 2 |
bar = 'force-upright'
# VSAQ = 1 ?
question = 'smooth'
# VSAT = 2 <>
decorative-angle-brackets = 'middle'

[buildPlans.ZhiMaMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.ZhiMaMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.ZhiMaMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.ZhiMaMono.subset.include]
ranges = [[0, 0x7f]]
